route:
  - match:
      severity: test-telegram
    receiver: stardata-telegram

receivers:
 
- name: 'stardata-telegram'
  telegram_configs:
  - bot_token: -4189215446
    api_url: https://api.telegram.org
    chat_id: '6551721742:AAFBNFQugY7zSLtSTj0dWdKNJ3axTlkM66s'
    parse_mode: ''
